apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-mind-observer.fullname" . }}-config
  labels:
    {{- include "kube-mind-observer.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DEBOUNCE_TTL_SECONDS: {{ .Values.config.debounceTTLSeconds | quote }}
  LEADER_ELECTION_NAMESPACE: {{ .Values.config.leaderElectionNamespace | default .Release.Namespace | quote }}
  LEADER_ELECTION_ID: {{ .Values.config.leaderElectionID | quote }}
  LEADER_ELECTION_RESOURCE_LOCK: {{ .Values.config.leaderElectionResourceLock | quote }}
  LEADER_ELECTION_LEASE_DURATION: {{ .Values.config.leaderElectionLeaseDuration | quote }}
  LEADER_ELECTION_RENEW_DEADLINE: {{ .Values.config.leaderElectionRenewDeadline | quote }}
  LEADER_ELECTION_RETRY_PERIOD: {{ .Values.config.leaderElectionRetryPeriod | quote }}
