apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-mind-observer.fullname" . }}-config
  labels:
    {{- include "kube-mind-observer.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DEBOUNCE_TTL_SECONDS: {{ .Values.config.debounceTTLSeconds | quote }}
