apiVersion: v1
kind: Service
metadata:
  name: kube-mind-brain-redis-master
  labels:
    {{- include "brain.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    {{- include "brain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
