apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brain.fullname" . }}-redis
  labels:
    {{- include "brain.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "brain.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "brain.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: "redis:alpine"
        ports:
        - containerPort: 6379
